-- copies 9690 pmids from pubmed generated by 
-- ("1900/1/1"[Date - Publication] : "2015/03/11"[Date - Publication])) AND ldl cholesterol reduction
-- the resuslts should be stored on /tmp as pubmed_result.csv before running the script

-- copy pnids into a table
drop table if exists temp_repatha_background1;
create table temp_repatha_background1 (pmid int);
copy temp_repatha_background1 from '/tmp/pubmed_result.csv' DELIMITER ',' CSV HEADER;

-- match to wos_ids
set enable_seqscan to 'off';
drop table if exists temp_repatha_background2;
create table temp_repatha_background2 as select a.pmid,b.wos_uid 
from temp_repatha_background1 a LEFT JOIN wos_pmid_mapping b 
on  a.pmid=b.pmid_int;


